POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "admin",
  "pwd": "admin",
  "authority": "ROLE_ADMIN"
}

###

POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "member",
  "pwd": "member",
  "authority": "ROLE_MEMBER"
}

###

POST http://localhost:8080/members
Content-Type: application/json

{
  "name": "guest",
  "pwd": "guest",
  "authority": "ROLE_GUEST"
}
