spring:
  messages:
    basename: messages/login
    encoding: UTF-8

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/security2;DATABASE_TO_UPPER=false;MODE=LEGACY;INIT=RUNSCRIPT FROM 'classpath:/script/schema.sql'
      username: sa
      password:

  jpa:
    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true

    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  ### TODO #1: redis connection 설정.
  redis:
    host: 127.0.0.1
    port: 6379
