spring:
  # TODO #2: resource bundle message source
  messages:
    basename: messages/login
    encoding: UTF-8

  # TODO #3: thymeleaf view template engine
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  # TODO #4: datasource w/ hikari cp
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/security;DATABASE_TO_UPPER=false;MODE=LEGACY
      username: sa
      password:

  # TODO #5: JPA 설정
  jpa:
    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        globally_quoted_identifiers: true

    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
